name: Python application

on:
  create
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Install system packages with apt
      run: sudo apt-get install libssl-dev libffi-dev
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Run setup script
      run: |
        python setup.py install
    - name: Install pex package from pip
      run: |
        pip install pex
    - name: Build multiplatform .pex Python executable
      run: |
        pex -v -o mastml.pex . -e mastml.mastml_driver:main --platform macosx_10.12 --platform macosx_10.13 --platform macosx_10.14 --platform linux-x86_64 --platform win32 --platform win_amd64
    - name: Release mastml.pex to GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: mastml.pex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
