name: Python application

on:
  create
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install mastml package from pip
      run: |
        python -m pip install --upgrade pip
        pip install mastml
    - name: Run setup script
      run: |
        python setup.py install
    - name: Install pex package from pip
      run: |
        pip install pex
    - name: Run pex
      run: |
        pex -o mastml.pex . -e mastml.mastml_driver:main --platform macosx_10.12-x86_64 --platform macosx_10.13-x86_64 --platform macosx_10.14-x86_64 --platform linux-x86_64 --platform linux-x86_64-cp-27-mu --platform win32 --platform win_amd64 --disable-cache
    - name: Release mastml.pex to GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: mastml.pex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
