name: Python application

on:
  create
  
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 3.7
      uses: actions/setup-python@v1
      with:
        python-version: 3.7
    - name: Install pex package from pip
      run: |
        pip install pex
    - name: Build multiplatform .pex Python executable
      run: |
        pex -v -o mastml.pex . -e mastml.mastml_driver:main --platform manylinux2010-x86_64-cp-37-m --platform win32-x32-cp-37-m --platform win_amd64-x86_64-cp-37-m --disable-cache
    - name: Release mastml.pex to GitHub
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        # Comma-delimited list of path globs for asset files to upload
        files: mastml.pex
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
